version: '3.8'

services:
  app:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: quanridor
      MONGO_INITDB_ROOT_PASSWORD: ps8vella
      # You can also specify the default authentication database if needed
      MONGO_INITDB_DATABASE: quanridor
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
